/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PassRouteImport } from './routes/pass'
import { Route as ParticipantsRouteImport } from './routes/participants'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FoodAdminRouteImport } from './routes/food-admin'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodTokenRegisterRouteImport } from './routes/food-token/register'
import { Route as FoodTokenLoginRouteImport } from './routes/food-token/login'
import { Route as FoodTokenDashboardRouteImport } from './routes/food-token/dashboard'
import { Route as AdminFoodTokensRouteImport } from './routes/admin/food-tokens'
import { Route as TokenVerifyTokenIdRouteImport } from './routes/token/verify.$tokenId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PassRoute = PassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodAdminRoute = FoodAdminRouteImport.update({
  id: '/food-admin',
  path: '/food-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodTokenRegisterRoute = FoodTokenRegisterRouteImport.update({
  id: '/food-token/register',
  path: '/food-token/register',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodTokenLoginRoute = FoodTokenLoginRouteImport.update({
  id: '/food-token/login',
  path: '/food-token/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodTokenDashboardRoute = FoodTokenDashboardRouteImport.update({
  id: '/food-token/dashboard',
  path: '/food-token/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFoodTokensRoute = AdminFoodTokensRouteImport.update({
  id: '/food-tokens',
  path: '/food-tokens',
  getParentRoute: () => AdminRoute,
} as any)
const TokenVerifyTokenIdRoute = TokenVerifyTokenIdRouteImport.update({
  id: '/token/verify/$tokenId',
  path: '/token/verify/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/food-admin': typeof FoodAdminRoute
  '/gallery': typeof GalleryRoute
  '/participants': typeof ParticipantsRoute
  '/pass': typeof PassRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/sponsors': typeof SponsorsRoute
  '/team': typeof TeamRoute
  '/admin/food-tokens': typeof AdminFoodTokensRoute
  '/food-token/dashboard': typeof FoodTokenDashboardRoute
  '/food-token/login': typeof FoodTokenLoginRoute
  '/food-token/register': typeof FoodTokenRegisterRoute
  '/token/verify/$tokenId': typeof TokenVerifyTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/food-admin': typeof FoodAdminRoute
  '/gallery': typeof GalleryRoute
  '/participants': typeof ParticipantsRoute
  '/pass': typeof PassRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/sponsors': typeof SponsorsRoute
  '/team': typeof TeamRoute
  '/admin/food-tokens': typeof AdminFoodTokensRoute
  '/food-token/dashboard': typeof FoodTokenDashboardRoute
  '/food-token/login': typeof FoodTokenLoginRoute
  '/food-token/register': typeof FoodTokenRegisterRoute
  '/token/verify/$tokenId': typeof TokenVerifyTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/food-admin': typeof FoodAdminRoute
  '/gallery': typeof GalleryRoute
  '/participants': typeof ParticipantsRoute
  '/pass': typeof PassRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/sponsors': typeof SponsorsRoute
  '/team': typeof TeamRoute
  '/admin/food-tokens': typeof AdminFoodTokensRoute
  '/food-token/dashboard': typeof FoodTokenDashboardRoute
  '/food-token/login': typeof FoodTokenLoginRoute
  '/food-token/register': typeof FoodTokenRegisterRoute
  '/token/verify/$tokenId': typeof TokenVerifyTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/events'
    | '/food-admin'
    | '/gallery'
    | '/participants'
    | '/pass'
    | '/register'
    | '/schedule'
    | '/sponsors'
    | '/team'
    | '/admin/food-tokens'
    | '/food-token/dashboard'
    | '/food-token/login'
    | '/food-token/register'
    | '/token/verify/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/events'
    | '/food-admin'
    | '/gallery'
    | '/participants'
    | '/pass'
    | '/register'
    | '/schedule'
    | '/sponsors'
    | '/team'
    | '/admin/food-tokens'
    | '/food-token/dashboard'
    | '/food-token/login'
    | '/food-token/register'
    | '/token/verify/$tokenId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/events'
    | '/food-admin'
    | '/gallery'
    | '/participants'
    | '/pass'
    | '/register'
    | '/schedule'
    | '/sponsors'
    | '/team'
    | '/admin/food-tokens'
    | '/food-token/dashboard'
    | '/food-token/login'
    | '/food-token/register'
    | '/token/verify/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FoodAdminRoute: typeof FoodAdminRoute
  GalleryRoute: typeof GalleryRoute
  ParticipantsRoute: typeof ParticipantsRoute
  PassRoute: typeof PassRoute
  RegisterRoute: typeof RegisterRoute
  ScheduleRoute: typeof ScheduleRoute
  SponsorsRoute: typeof SponsorsRoute
  TeamRoute: typeof TeamRoute
  FoodTokenDashboardRoute: typeof FoodTokenDashboardRoute
  FoodTokenLoginRoute: typeof FoodTokenLoginRoute
  FoodTokenRegisterRoute: typeof FoodTokenRegisterRoute
  TokenVerifyTokenIdRoute: typeof TokenVerifyTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-admin': {
      id: '/food-admin'
      path: '/food-admin'
      fullPath: '/food-admin'
      preLoaderRoute: typeof FoodAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-token/register': {
      id: '/food-token/register'
      path: '/food-token/register'
      fullPath: '/food-token/register'
      preLoaderRoute: typeof FoodTokenRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-token/login': {
      id: '/food-token/login'
      path: '/food-token/login'
      fullPath: '/food-token/login'
      preLoaderRoute: typeof FoodTokenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-token/dashboard': {
      id: '/food-token/dashboard'
      path: '/food-token/dashboard'
      fullPath: '/food-token/dashboard'
      preLoaderRoute: typeof FoodTokenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/food-tokens': {
      id: '/admin/food-tokens'
      path: '/food-tokens'
      fullPath: '/admin/food-tokens'
      preLoaderRoute: typeof AdminFoodTokensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/token/verify/$tokenId': {
      id: '/token/verify/$tokenId'
      path: '/token/verify/$tokenId'
      fullPath: '/token/verify/$tokenId'
      preLoaderRoute: typeof TokenVerifyTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFoodTokensRoute: typeof AdminFoodTokensRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFoodTokensRoute: AdminFoodTokensRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FoodAdminRoute: FoodAdminRoute,
  GalleryRoute: GalleryRoute,
  ParticipantsRoute: ParticipantsRoute,
  PassRoute: PassRoute,
  RegisterRoute: RegisterRoute,
  ScheduleRoute: ScheduleRoute,
  SponsorsRoute: SponsorsRoute,
  TeamRoute: TeamRoute,
  FoodTokenDashboardRoute: FoodTokenDashboardRoute,
  FoodTokenLoginRoute: FoodTokenLoginRoute,
  FoodTokenRegisterRoute: FoodTokenRegisterRoute,
  TokenVerifyTokenIdRoute: TokenVerifyTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
